//go:build linux && (amd64 || arm64)

// Code generated by go:generate; DO NOT EDIT.

package main

import _ "embed"

//go:embed ../binaries/firecracker
var firecrackerBinary []byte

// GetFirecrackerBinary returns the embedded firecracker binary
func GetFirecrackerBinary() []byte {
	return firecrackerBinary
}