name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        go-version:
          - "1.25.1"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: go mod download

      - name: Generate binaries
        run: go generate ./...

      - name: Build
        run: CGO_ENABLED=0 go build ./cmd/ssh-hypervisor

      - name: Check binary works
        run: ./ssh-hypervisor -version

      - name: Add runner to KVM ACL
        run: sudo setfacl -m u:"$(whoami)":rw /dev/kvm

      - name: Run tests
        run: go test -v -exec sudo ./...
